AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CodeDeploy role, in dev & prod account

Resources:
  CodeDeployRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: 'sts:AssumeRole'
      RoleName: cicd_codedeploy_role
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

Outputs:
  CodeDeployRoleARN:
    Value: !GetAtt CodeDeployRole.Arn
