AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CodePipeline role of dev account

Parameters:
  ProductionAccountID:
    Description: ID of Production account
    Type: String
    Default: ''

Resources:
  PipelineRolePolicies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: cicd_codepipeline_role_policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowCodeCommitActions
            Action:
              - 'codecommit:CancelUploadArchive'
              - 'codecommit:GetBranch'
              - 'codecommit:GetCommit'
              - 'codecommit:GetUploadArchiveStatus'
              - 'codecommit:UploadArchive'
            Resource: '*'
            Effect: Allow
          - Sid: AllowS3ObjectAccessOnCodePipelineBuckets
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:GetObjectVersion'
              - 's3:GetBucketAcl'
              - 's3:GetBucketLocation'
            Resource: '*'
            Effect: Allow
          - Sid: AllowCodeBuildActions
            Action:
              - 'codebuild:BatchGetBuilds'
              - 'codebuild:StartBuild'
            Resource: '*'
            Effect: Allow
          - Sid: AllowCodeDeployActions
            Action:
              - 'codedeploy:CreateDeployment'
              - 'codedeploy:GetApplication'
              - 'codedeploy:GetApplicationRevision'
              - 'codedeploy:GetDeployment'
              - 'codedeploy:GetDeploymentConfig'
              - 'codedeploy:RegisterApplicationRevision'
            Resource: '*'
            Effect: Allow
          - Sid: AllowAssumeRoleCrossAccount
            Effect: Allow
            Action: 'sts:AssumeRole'
            Resource:
              - !Sub 'arn:aws:iam::${ProductionAccountID}:role/cicd_codepipeline_cross_account_role'
      Roles:
        - !Ref codepipelineRole

  codepipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      RoleName: cicd_codepipeline_role
      Path: /

Outputs:
  codepipelineRoleARN:
    Value: !GetAtt codepipelineRole.Arn
